# Book settings
title: AReaL HCU Documentation
author: Hygon Information Technology Co., Ltd.
copyright: "Copyright (c) 2026 Hygon Information Technology Co., Ltd."
logo: ../figures/logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

html:
  use_issues_button: false
  use_repository_button: false
  extra_footerjs:
    - _static/js/lang-toggle.js
  extra_css:
    - _static/css/lang-toggle.css

build:
  dir: ../_build/en
  figureurl: /figures

sphinx:
  config:
    html_extra_path:
      - _static
      - ../figures
